inventory/api/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from . import views

urlpatterns = [
    path('home/', views.home ), 
    path('login/', views.login ), 
    path('signup/', views.signup),
    path('product_description/<int:pk>', views.product_description),
    path('return_form/', views.return_form),
    path('return_all/<int:item_id>/', views.return_all),
    
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


"""
    #Admin-and-superadmin
    path('admin_views/', views.admin_view, name='admin_views'),
    path('add_product/', views.add_product ,name="Add_product"), 
    path('add_category/', views.add_category, name="Add_category"),
    path('wastage_render/', views.wastage, name='wastage_render'),
    
    #access-denied-page
    path('no_permisson/', views.no_permission, name='no_permission'),
    path('forbidden/', views.custom_forbidden, name='custom_forbidden'),

    #superadmin
    path('users/', views.users_list, name='users_list'),
    # path('appoint_admin/<int:user_id>/', views.appoint_admin, name='appoint_admin'),
    path('remove_role/<int:user_id>/', views.remove_role, name='remove_role'),

    #cart
    path('cart/', views.view_cart, name='view_cart'),

    #Return-form
    path('add_wastage/<int:item_id>/', AddWastageView.as_view(), name="Add_wastage"),
    path('return/<int:item_id>/', AddReturnView.as_view(), name="return"),
    """

inventory/invention/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth.views import LogoutView
from .views import return_form, AddWastageView, AddReturnView

urlpatterns = [
    #authentication
    path('login/', views.login ,name="login"), 
    path('signup/', views.signup ,name="Register"), 
    path('complete/azuread-tenant-oauth2/home/', views.home ,name="Home"),
    path('logout/', LogoutView.as_view() , name="logout"),

    #Home-Page-And-navbar-page-For-Users
    path('', views.home ,name="Home"), 
    path('about/', views.about , name="About"),
    path('product_description/<int:pk>/', views.product_description, name="Product_description"),

    #Admin-and-superadmin
    path('admin_views/', views.admin_view, name='admin_views'),
    path('wastage_render/', views.wastage, name='wastage_render'),
    
    #Product
    path('add_product/', views.add_product ,name="Add_product"), 
    path('product/', views.view_product, name="product"),
    path('remove_product/<int:pk>/', views.remove_product, name="delete_product"),
    path('edit_product_view/<int:product_id>/', views.edit_product_view , name="edit_product_view"),
 

    #Category
    path('add_category/', views.add_category, name="Add_category"),
    path('category/', views.category, name= "category"),
    path('delete_category/<int:category_id>/', views.remove_category, name="delete_category"),
    path('edit_category/<int:category_id>/', views.edit_category, name="edit_category"),
    

    #Sub-Category
    path('add_subcategory/', views.add_subcategory, name="Add_subcategory"),
    path('delte_subcategory/<int:subcategory_id>/', views.remove_subcategory, name="delete_subcategory"),
    path('edit_subcategory/<int:subcategory_id>/', views.edit_subcategory, name="edit_subcategory"),
    path('sub_category/', views.sub_category, name="sub_category"),

    #access-denied-page
    path('no_permisson/', views.no_permission, name='no_permission'),
    path('forbidden/', views.custom_forbidden, name='custom_forbidden'),

    #superadmin
    path('users/', views.users_list, name='users_list'),
    # path('appoint_admin/<int:user_id>/', views.appoint_admin, name='appoint_admin'),
    path('remove_role/<int:user_id>/', views.remove_role, name='remove_role'),

    #cart
    path('cart/', views.view_cart, name='view_cart'),
    path('add/<int:product_id>/', views.add_to_cart, name="add_to_cart"),
    path('remove_from_cart/<int:product_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/submit/', views.submit_cart, name='submit_cart'),
    # path('increase_quantity/<int:product_id>/', views.increase_quantity, name='increase_quantity'),
    # path('decrease_quantity/<int:product_id>/', views.decrease_quantity, name='decrease_quantity'),
    # path('update_quantity/<int:product_id>/<int:quantity>/', views.update_quantity, name='update_quantity'),

    #Return-form
    path('return_form/', views.return_form, name="return_form"),
    path('return_all/<int:item_id>/', views.return_all, name='return_all'),
    path('add_wastage/<int:item_id>/', AddWastageView.as_view(), name="Add_wastage"),
    path('return/<int:item_id>/', AddReturnView.as_view(), name="return"),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

inventory/inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('invention.urls')),
    path('api/', include('api.urls')),
    path('', include('social_django.urls', namespace='social'))
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL , document_root=settings.MEDIA_ROOT)

inventory/invention/models.py
from django.db import models
from django.db.models import F
from django.contrib.auth.models import User
from django.utils import timezone
import datetime
# from datetime.timezone import tz

class Signup(models.Model):
  username = models.CharField(max_length=100)
  password = models.CharField(max_length=100)
  con_password = models.CharField(max_length=100)


class login(models.Model):
  username = models.CharField(max_length=100)
  password = models.CharField(max_length=100)


class Product(models.Model):
    name=models.CharField(max_length=255)
    decription=models.CharField(max_length=100)
    actual_count=models.PositiveIntegerField()
    available_count=models.PositiveIntegerField()
    dummy_count = models.PositiveIntegerField()
    category= models.ForeignKey('Category', on_delete=models.CASCADE)
    sub_category = models.ForeignKey('SubCategory', on_delete = models.CASCADE)
    created_at = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='images')
    actual_price = models.PositiveIntegerField()
    available_price = models.PositiveIntegerField()
    unit_price = models.FloatField()
    is_active = models.BooleanField(default = False)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.name)

 
class Category(models.Model):
    name=models.CharField(max_length=25)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = 'Categories'

    def __str__(self):
        return str(self.name)

class SubCategory(models.Model):
    name_sub=models.CharField(max_length=25)
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    created_at=models.DateTimeField(auto_now=True)

    def __str__(self):
      return self.name_sub
    
temporary_cart = {} 

class Cart(models.Model):
    product_name=models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField(default=0)
    created_by=models.ForeignKey(User,on_delete=models.CASCADE)

    def __str__(self):
        return str(self.product_name)


class Wastage(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product_name=models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity=models.PositiveIntegerField()
    reason=models.TextField()
    category = models.ForeignKey('Category', on_delete=models.CASCADE)
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return str(self.user) 


class PurchasedItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    date_added = models.DateTimeField() 
    status = models.CharField(max_length=20, choices=[('checked_in','checked_in'),('checked_out','checked_out')])
    due_date = models.DateTimeField()
    email_sent = models.BooleanField(default=False)
    
    def _str_(self):
        return str(self.product)

    
class Log(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(timezone.now)
    status = models.CharField(max_length=20, choices=[('checked_in','checked_in'),('checked_out','checked_out')])
    acting = models.CharField(max_length=20, default="hi")
    due_date = models.DateTimeField()
    def _str_(self):
        return str(self.product)

class CheckedOutLog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey('Product', on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(default=timezone.now)
    status = models.CharField(max_length=20, choices=[('checked_in','checked_in'),('checked_out','checked_out')])

    def _str_(self):
        return str(self.product)

class AdminMail(models.Model):
    mail=models.CharField(max_length=50)


class Stock(models.Model):
    name = models.CharField(max_length=255) 
    actual_stock = models.PositiveIntegerField() 
    available_stock = models.PositiveIntegerField()
    actual_price = models.FloatField() 
    available_price = models.FloatField()
    unit_price = models.FloatField()
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    sub_category = models.ForeignKey('SubCategory', on_delete=models.CASCADE)

    def __str__(self):
      return self.name

inventory/invention/forms.py
from django import forms
from .models import *

class NewCategoryForm(forms.ModelForm):
  class Meta:
    model = Category
    fields = ('name',)

    widgets = {
      'name': forms.TextInput(attrs={
        'placeholder': 'Enter the Category',
      }),
    }

inventory/invention/templates/cart/cart.html
{% extends "base.html" %}

{% load static %}


{% block base %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
  <style>
    /* Your existing custom styles */
  </style>
  <script>
    function confirmRemoveItem(itemId) {
      const confirmation = confirm("Are you sure you want to remove this item from the cart?");
      if (confirmation) {
        document.getElementById(`removeItem_${itemId}`).submit();
      } else {
        return false;
      }
    }
  
    function confirmSubmitCart() {
      const confirmation = confirm("It's okay to submit the cart with these items?");
      if (confirmation) {
        document.getElementById('submitCartForm');
      } else {
        return false;
      }
    }
  </script>
</head>
<body>
  <section class="vh-100 d-flex align-items-center">
    <div class="container py-5">
      <div class="card shadow-lg border-radius-15">
        <div class="card-body">
          <div class="mb-4">
            <h1 class="fw-bold mb-0">Cart-items-{{cart}}</h1>
          </div>
          <hr class="my-4">
          <div class="table-responsive">
            <table class="table">
              <thead>
                <tr>
                  <th>Image</th>
                  <th>Product Name</th>
                  <th>Quantity</th>
                  <th>Category</th>
                  <th>Remove Item</th>
                </tr>
              </thead>
              <tbody>
               
                {% for item in cart_items %}
                <tr>
                  <td><img src="{{item.product_name.image.url}}" alt="{{ item.product_name.name }}" class="img-fluid shadow-sm border border-black" height="150" width="200"></td>
                  <td>{{ item.product_name.name }}</td>
                  <td>{{ item.quantity }}</td>
                  <td>{{ item.product_name.category }}</td>

                  <td>
                    <form action="{% url 'remove_from_cart' product_id=item.id %}" method="post" id="removeItem_{{ item.id }}">
                      {% csrf_token %}
                      <button type="button" class="btn btn-danger btn-sm" onclick="return confirmRemoveItem('{{ item.id }}')">Remove</button>
                    </form>
                  </td>
                </tr>
                {% empty %}
                <tr>
                  <td colspan="5"><p>No items</p></td>
                </tr>
                {% endfor %}
              </tbody>
            </table>
          </div>
          <hr class="my-4"> 
          <div class="row">
            <div class="col-md-6 mb-3">
              <a href="{% url 'Home' %}" class="btn btn-secondary"><i class="fas fa-long-arrow-alt-left me-2"></i>Back to Home</a>
            </div>
            <div class="col-md-6 text-end">
              <form id="submitCartForm" action="{% url 'submit_cart' %}" method="post">
                {% csrf_token %}
                <div>
                  <label>Due Date :</label>
                  <input type="date" name="due_date" id="id_due_date" required>
                </div>
                <br>
                <!-- <input type="button" value="Submit Cart" class="btn btn-primary" onclick="return confirmSubmitCart()"> -->
                <button type="submit" class="btn btn-primary" value="Submit Cart" onclick="return confirmSubmitCart()">Submit Cart</button>
              </form>
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js" integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+" crossorigin="anonymous"></script>
<script>
  document.addEventListener('DOMContentLoaded', function () {
      var today = new Date().toISOString().split('T')[0];
      var oneMonthLater = new Date();
      oneMonthLater.setMonth(oneMonthLater.getMonth() + 1);
      var maxDate = oneMonthLater.toISOString().split('T')[0];
      document.getElementById('id_due_date').min = today;
      document.getElementById('id_due_date').max = maxDate;
  });
</script>
{% endblock %}

inventory/invention/templates/cart/return.html
{% extends 'base.html' %}

{% block base %}
<style>
  #waste {
    margin-top: 75px;
  }
  .form-card {
    background-color: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
  }
  .custom-label {
    font-weight: bold;
  }
</style>

<div class="p-4" id="waste">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="form-card shadow p-4 mb-4">
          <h1 class="text-center mb-4">Return Form</h1>
          <form method="POST" id="productForm">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="product-name" class="form-label custom-label">Product Name</label>
                  <input type="text" class="form-control" id="product-name" name="product_name" value="{{ item.product.name }}" readonly>
                </div>
                <div class="mb-3">
                  <label for="category" class="form-label custom-label">Category</label>
                  <input type="text" class="form-control" id="category" name="category" value="{{ item.product.category }}" readonly>
                </div>
                <div class="mb-3">
                  <label for="actual-quantity" class="form-label custom-label">Actual Quantity</label>
                  <p>{{ item.product.actual_count }}</p>
                </div>
                <div class="mb-3">
                  <label for="taken-quantity" class="form-label custom-label">Taken Quantity</label>
                  <p>{{ item.quantity }}</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="taken-date" class="form-label custom-label">Taken Date</label>
                  <p>{{ item.created_at }}</p>
                </div>
                <div class="mb-3">
                  <label for="damaged-quantity" class="form-label custom-label">Return Quantity</label>
                  <input type="number" min="0" value="0" class="form-control" id="damaged-quantity" name="return_qty" required>
                </div>
                <button type="submit" class="btn btn-primary mt-3" onclick="return confirmSubmitCart()">Submit</button>
              </div>
            </div>
          </form>
          <div class="message mt-4">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function confirmSubmitCart() {
    const confirmation = confirm("It's okay to submit");
    if (confirmation) {
      document.getElementById('productForm').submit();
    } else {
      return false;
    }
  }

  document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('form');

    form.addEventListener('submit', function(event) {
      event.preventDefault();

      const damagedQuantity = parseInt(document.querySelector('input[name="return_qty"]').value);
      const takenQuantity = parseInt('{{ item.quantity }}');

      if (damagedQuantity <= 0) {
        alert('OOPS!! Quantity should not be Zero.');
        return;
      }

  
      if (damagedQuantity > takenQuantity) {
        alert('Enter the correct quantity.');
        return;
      }

      form.submit();
    });
  });
</script>
{% endblock %}

inventory/invention/templates/cart/return_form.html
{% extends 'base.html' %}

{% block base %}
<body class="bg-gray-100">
  <div class="container py-4">
    <h1 class="text-center text-orange mb-4">Return Form</h1>
    <div class="row row-cols-1 row-cols-md-3 g-4">
      {% for item in purchased_items %}
      <div class="col">
        <div class="card shadow">
          <div class="card-body">
            <h2 class="fw-bold">Checked In:</h2>
            <p>Product Name: {{ item.product.name }}</p>
            <p>Product Quantity: {{ item.quantity }}</p>
            <p>Category: {{ item.product.category }}</p>
            <p>Date & Time: {{ item.created_at}}</p>
            <div class="d-flex justify-content-between align-items-center mt-3">
            {% if item.quantity != 1 %}
              <form action="{% url 'return' item.pk %}" method="post">
                {% csrf_token %}
                <button type="submit" id="return-button" class="btn btn-primary me-2">Return</button>
              </form>
            {% endif %}
              <form action="{% url 'return_all' item.id %}" method="get">
                {% csrf_token %}
                <button type="submit" id="return-all-button" class="btn btn-primary">Return All</button>
              </form>
              <form action="{% url 'Add_wastage' item.id %}" >
                {% csrf_token %}
                <button type="submit" id="damaged-button" class="btn btn-danger">Damaged</button>
              </form>
            </div>
          </div>
        </div>
      </div>
      {% empty %}
      <div class="col">
        <div class="card shadow">
          <div class="card-body">
            <p class="text-center">No Returns Yet</p>
          </div>
        </div>
      </div>
      {% endfor %}
    </div>
  </div>
  <div class="mb-5 mt-5">
    .
  </div>
  <script>
  function debounce(func, delay) {
    let timer;
    return function () {
        const context = this;
        const args = arguments;
        clearTimeout(timer);
        timer = setTimeout(() => {
            func.apply(context, args);
        }, delay);
    };
}

function delayfuction() {
    alert('You have enter multiple times. Please wait for 5 seconds');
}

const button = document.getElementById('return-button');
button.addEventListener('click', debounce(delayfuction(), 300)); 

const button = document.getElementById('return-all-button');
button.addEventListener('click', debounce(delayfuction(), 300));

const button = document.getElementById('damaged-button');
button.addEventListener('click', debounce(delayfuction(), 300));
</script>
</body>
{% endblock %}

inventory/invention/templates/cart/wastage.html
{% extends 'base.html' %}

{% block base %}
<style>
  #waste {
    margin-top: 75px;
  }
  .form-card {
    background-color: #f8f9fa;
    border-radius: 15px;
    padding: 30px;
  }
  .custom-label {
    font-weight: bold;
  }
</style>


<div class="p-4" id="waste">
  <div class="container">
    <div class="row justify-content-center">
      <div class="col-lg-8">
        <div class="form-card shadow p-4 mb-4">
          <h1 class="text-center mb-4">Wastage Form</h1>
          <form method="POST" id="wastageForm">
            {% csrf_token %}
            <div class="row">
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="product-name" class="form-label custom-label">Product Name</label>
                  <input type="text" class="form-control" id="product-name" name="product_name" value="{{ item.product.name }}" readonly>
                </div>
                <div class="mb-3">
                  <label for="category" class="form-label custom-label">Category</label>
                  <input type="text" class="form-control" id="category" name="category" value="{{ item.product.category }}" readonly>
                </div>
                <div class="mb-3">
                  <label for="actual-quantity" class="form-label custom-label">Actual Quantity</label>
                  <p>{{ item.product.actual_count }}</p>
                </div>
                <div class="mb-3">
                  <label for="taken-quantity" class="form-label custom-label">Taken Quantity</label>
                  <p>{{ item.quantity }}</p>
                </div>
              </div>
              <div class="col-md-6">
                <div class="mb-3">
                  <label for="taken-date" class="form-label custom-label">Taken Date</label>
                  <p>{{ item.created_at }}</p>
                </div>
                <div class="mb-3">
                  <label for="damaged-quantity" class="form-label custom-label">Damaged Quantity</label>
                  <input type="number" min="0" value="0" class="form-control" name="damaged_qty" required>
                </div>
                <div class="mb-3">
                  <label for="reason" class="form-label custom-label">Reason</label>
                  <input type="text" class="form-control" id="damaged-quantity" name="reason" required>
                </div>
                <button type="submit" class="btn btn-primary mt-3" onclick="return confirmSubmitCart()">Submit</button>
              </div>
            </div>
          </form>
          <div class="message mt-4">
            {% for message in messages %}
            <p>{{ message }}</p>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
<script>
  function confirmSubmitCart() {
    const confirmation = confirm("It's okay to submit");
    if (confirmation) {
      document.getElementById('productForm').submit();
    } else {
      return false;
    }
  }
  document.addEventListener('DOMContentLoaded', function() {
    const form = document.querySelector('form');

    form.addEventListener('submit', function(event) {
      event.preventDefault();

      const damagedQuantity = parseInt(document.querySelector('input[name="damaged_qty"]').value);
      const takenQuantity = parseInt('{{ item.quantity }}'); 

      if (damagedQuantity <= 0) {
        alert('OOPS!! Quantity should not be Zero.');
        return;
      }

      if (damagedQuantity > takenQuantity) {
        alert('Enter the correct quantity.');
        return;
      }

      form.submit();
    });
  });
</script>
{% endblock %}